#!/usr/bin/env bash

set -euo pipefail
export DOCKER_IMAGE="gcr.io/banba-group/vayu.com.au:${BUILDKITE_COMMIT}"
echo "--- :kubernetes: deploying ${DOCKER_IMAGE} to kubernetes"

if [ -z "${DOCKER_IMAGE:-}" ]; then
  echo ":boom: \$DOCKER_IMAGE missing" 1>&2
  exit 1
fi

manifest="$(mktemp)"
echo '--- :kubernetes: Shipping'
gcloud config set project banba-group
gcloud run deploy vayu-com-au --image $DOCKER_IMAGE --region us-central1

# gcloud container clusters get-credentials production --zone us-central1-a
# envsubst < k8s/production/deployment.yaml > "${manifest}"
# kubectl apply -f "${manifest}"

# echo '--- :zzz: Waiting for deployment'
# #kubectl wait --for condition=available --timeout=150s -f "${manifest}"

# ATTEMPTS=0
# ROLLOUT_STATUS_CMD="kubectl rollout status deployment vayu-com-au --namespace=www-vayu-com-au"
# until $ROLLOUT_STATUS_CMD || [ $ATTEMPTS -eq 100 ]; do
#     $ROLLOUT_STATUS_CMD
#     ATTEMPTS=$((attempts + 1))
#     echo "."
#     sleep 10
# done

# if ! kubectl rollout status deployment vayu-com-au --namespace=www-vayu-com-au; then
#     echo "Failed to deploy; rolling back the deployment"
#     kubectl rollout undo deployment vayu-com-au --namespace=www-vayu-com-au
#     kubectl rollout status deployment vayu-com-au --namespace=www-vayu-com-au
#     exit 1
# fi
