---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "vayu-com-au"
  namespace: "www-vayu-com-au"
  labels:
    app: "vayu-com-au"
spec: 
  replicas: 3
  selector:
    matchLabels:
      app: "vayu-com-au"
  template:
    metadata:
      labels:
        app: "vayu-com-au"
    spec:
      containers:
        - name: "vayu-com-au"
          image:  "${DOCKER_IMAGE}"          
          imagePullPolicy: "Always"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            failureThreshold: 3
            periodSeconds: 3
          startupProbe:
            httpGet:
              path: /
              port: 80
            failureThreshold: 30
            periodSeconds: 100          
          ports:
          - containerPort: 80
      nodeSelector:
        pool: preemptible            
---
apiVersion: "autoscaling/v1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "vayu-com-au-hpa"
  namespace: "www-vayu-com-au"
  labels:
    app: "vayu-com-au"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "vayu-com-au"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 6
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-dns
  namespace: kube-system
data:
  upstreamNameservers: |
    [ "8.8.8.8", "8.8.4.4" ]
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "vayu-com-au-service"
  namespace: "www-vayu-com-au"
  labels:
    app: "vayu-com-au"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  selector:
    app: "vayu-com-au"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: www-vayu-com-au-limit-range
  namespace: "www-vayu-com-au"
spec:
  limits:
  - default:
      memory: 25Mi
    defaultRequest:
      memory: 15Mi
    type: Container
