---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "vayu-com-au"
  namespace: "default"
  labels:
    app: "vayu-com-au"
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: "vayu-com-au"
  template:
    metadata:
      labels:
        app: "vayu-com-au"
    spec:
      containers:
        - name: "vayu-com-au"
          image:  "${DOCKER_IMAGE}"          
          imagePullPolicy: "Always"
          #resources:
          #  limits:
          #    memory: 12Mi
          #  requests:
          #    memory: 6Mi
          ports:
          - containerPort: 80
---
apiVersion: "autoscaling/v1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "vayu-com-au-hpa"
  namespace: "default"
  labels:
    app: "vayu-com-au"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "vayu-com-au"
    apiVersion: "apps/v1beta1"
  minReplicas: 1
  maxReplicas: 6
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-dns
  namespace: kube-system
data:
  upstreamNameservers: |
    [ "8.8.8.8", "8.8.4.4" ]
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "vayu-com-au-service"
  namespace: "default"
  labels:
    app: "vayu-com-au"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  selector:
    app: "vayu-com-au"
